FROM php:8.2-fpm

# Expose port 9000
EXPOSE 9000

# Install dependencies and PHP extentions
RUN apt-get update && apt-get install -y \
	libzip-dev \
	libicu-dev \
	libpq-dev \
	zlib1g-dev \
	libpng-dev \
	libjpeg-dev \
	libfreetype6-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install gd mysqli pdo pdo_mysql intl zip \
	&& pecl install igbinary redis \
	&& docker-php-ext-enable igbinary redis mysqli

